url=jdbc:postgresql://mi_postgres:5432/prueba
username=postgres
password=Postgresql
driver=org.postgresql.Driver
changeLogFile=/liquibase/changelog/changelog/db.changelog-master.xml
classpath=/liquibase/changelog/drivers/postgresql-42.6.0.jar